version: '3.7'

services:
  app:
    build:
      context: .
    image: nodejs
    env_file:
      - .env.prod
    ports:
      - "0.0.0.0:3000:8080"
    container_name: quest
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres:12.2-alpine
    env_file:
      - .env.prod
    volumes:
      - ./pgdata:/var/lib/postgresql/data
